# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Card_Receive_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtp_date', models.DateField(verbose_name='RTP Date')),
                ('received_box_amount', models.IntegerField(verbose_name='Box Amount Received')),
                ('received_date', models.DateField(verbose_name='Date Received')),
                ('received_amount', models.IntegerField(verbose_name='Amount Received')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_overview.ID_Card', to_field='card_type')),
            ],
            options={
                'verbose_name': 'Card Stock Received Record',
                'verbose_name_plural': 'Card Stock Received Records',
            },
        ),
    ]
