# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, unique=True, verbose_name='ID Type')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ID Type',
                'verbose_name_plural': 'ID Types',
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Office Name')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.AddField(
            model_name='idtypes',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.Offices'),
        ),
    ]
