# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, unique=True, verbose_name='Course')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=200, unique=True, verbose_name='Department')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Description')),
                ('id_type', models.ManyToManyField(blank=True, to='app_reference.IDTypes')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200, unique=True, verbose_name='Level')),
                ('description', models.TextField(verbose_name='Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.Departments')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Strands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=200, unique=True, verbose_name='Strand')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Description')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.Departments')),
            ],
            options={
                'verbose_name': 'Strand',
                'verbose_name_plural': 'Strands',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.Departments'),
        ),
    ]
