# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_auto_20170824_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=200, unique=True, verbose_name='Layout Name')),
                ('layout_code', models.CharField(max_length=200, verbose_name='Layout Code')),
                ('layout_front', models.ImageField(upload_to='idlayouts/front', verbose_name='Front Layout')),
                ('layout_back', models.ImageField(upload_to='idlayouts/back', verbose_name='Back Layout')),
                ('description', models.TextField(verbose_name='Description')),
                ('id_type', models.ManyToManyField(blank=True, to='app_reference.IDTypes')),
            ],
            options={
                'verbose_name': 'Card Layout',
                'verbose_name_plural': 'Card layouts',
            },
        ),
    ]
