# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_cardslayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_type', models.CharField(max_length=200, unique=True, verbose_name='Employment Type')),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_reference.CardsLayout')),
            ],
            options={
                'verbose_name': 'Employment Type',
                'verbose_name_plural': 'Emplotment Types',
            },
        ),
    ]
