# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reference', '0001_initial'),
        ('app_printers', '0001_initial'),
        ('app_ribbons', '0001_initial'),
        ('app_overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDPrintRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, verbose_name='ID No.')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('bad_print', models.IntegerField(verbose_name='Bad Print')),
                ('print_date', models.DateField(verbose_name='Print Date')),
                ('id_status', models.CharField(choices=[('CLA', 'Claimed'), ('PRI', 'Printed')], default='CLA', max_length=3, verbose_name='ID Status')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_overview.Active_Stocks')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.IDTypes')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_printers.Printers', to_field='printer_name')),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ribbons.RibbonUsageRecord', to_field='ribbon_number')),
            ],
            options={
                'verbose_name': 'ID Print Record',
                'verbose_name_plural': 'ID Print Records',
                'permissions': (('can_add_all_types', 'Add all print types'), ('can_add_alumni_types', 'Add Alumni print types'), ('can_add_student_types', 'Add Student print types'), ('can_add_employee_types', 'Add Employee print types'), ('can_add_hospital_types', 'Add Hospital print types')),
            },
        ),
    ]
