# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_overview', '0001_initial'),
        ('app_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField(verbose_name='Use Date')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_overview.Active_Stocks')),
            ],
            options={
                'verbose_name': 'Card Usage History',
                'verbose_name_plural': 'Card Usage Histories',
            },
        ),
    ]
