# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0002_cardusagehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardusagehistory',
            options={'verbose_name': 'Card Usage Record', 'verbose_name_plural': 'Card Usage Reords'},
        ),
    ]
