# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0003_auto_20170824_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idprintrecord',
            options={'verbose_name': 'ID Print Record', 'verbose_name_plural': 'ID Print Records'},
        ),
    ]
