# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200, unique=True, verbose_name='Stock Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Amount')),
            ],
            options={
                'verbose_name': 'Active Stock',
                'verbose_name_plural': 'Active Stocks',
            },
        ),
        migrations.CreateModel(
            name='ID_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=200, unique=True, verbose_name='Card Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Amount')),
            ],
            options={
                'verbose_name': 'ID Card',
                'verbose_name_plural': 'ID Cards',
            },
        ),
        migrations.CreateModel(
            name='Printer_Ribbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ribbon_type', models.CharField(max_length=200, unique=True, verbose_name='Ribbon Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Amount')),
            ],
            options={
                'verbose_name': 'Printer Ribbon',
                'verbose_name_plural': 'Printer Ribbons',
            },
        ),
        migrations.AddField(
            model_name='active_stocks',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_overview.ID_Card', to_field='card_type'),
        ),
        migrations.AddField(
            model_name='active_stocks',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.Offices'),
        ),
    ]
