# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_overview', '0003_auto_20170926_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_overview.Active_Stocks'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_printers.Printers'),
        ),
    ]
