# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_overview', '0004_auto_20170927_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='all_types',
            field=models.BooleanField(default=True, verbose_name='All ID Types'),
        ),
    ]
