# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=200, unique=True, verbose_name='Printer Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], max_length=1, verbose_name='Status')),
                ('total_printed', models.IntegerField(verbose_name='Total Printed')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.Offices')),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
            },
        ),
    ]
