# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer_Ribbon_Receive_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtp_date', models.DateField(verbose_name='RTP Date')),
                ('received_date', models.DateField(verbose_name='Date Received')),
                ('received_amount', models.IntegerField(verbose_name='Amount Received')),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_overview.Printer_Ribbon', to_field='ribbon_type')),
            ],
            options={
                'verbose_name': 'Ribbon Stock Received Record',
                'verbose_name_plural': 'Ribbon Stock Received Records',
            },
        ),
    ]
