# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_id_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_form',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='id_form',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='sigs', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='id_form',
            name='year_grad',
            field=models.CharField(max_length=50, null=True, verbose_name='Year Graduated'),
        ),
    ]
