# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_id_form', '0002_auto_20170919_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_form',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='id_form',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='id_form',
            name='middle_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='id_form',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
